### ISSUE TITLE
Site keep saying my password is incorrect.

### ISSUE THREAD

**Issue by ottoman42** [matt-dale/designdbonline#39]
I have been trying to log in and the website keeps saying my password is incorrect. I change the password with the forgot password link and it still says the password and user name are incorrect. Though both are the same thing I entered in the password reset fields.

**Comment by ottoman42** [comment]
nevemrind. It seemed to work now with the password saved in Safari, guess the issue was on my end. Sorry!

**Comment by matt-dale** [comment]
Turns out this is an issue! 

If the email was entered with capital letters, then that is how the username was saved in the database.  So you actually have two user accounts created, one with a capital M and one with a lowercase m. 

I will fix that tomorrow.
